refactor(local): added extra logging for local activation
open-amt-cloud-toolkit/rpc-go pull request #328
Opened 2024-01-09 20:23 UTC by zaidusmani26

2024-01-17 16:18 UTC, Craig-Spencer-12 approved these changes
LGTM

2024-01-17 16:22 UTC, rsdmike requested changes

2024-01-17 16:22 UTC, rsdmike commented on internal/local/activate.go
> +	if service.flags.Verbose {
You shouldn't need the condition -- the log level sets when these should be logged

2024-01-17 16:22 UTC, rsdmike commented on internal/local/activate.go
> +	if service.flags.Verbose {
Remove condition

2024-01-17 16:22 UTC, rsdmike commented on internal/local/activate.go
> +	if service.flags.Verbose {
Remove condition

2024-01-17 16:22 UTC, rsdmike commented on internal/local/activate.go
> +	if service.flags.Verbose {
Remove condition

2024-01-17 16:22 UTC, rsdmike commented on internal/local/activate_test.go
> +	f.Verbose = true
I don't think we turn this on in testing as will put a lot of noise into the console.

2024-01-19 22:35 UTC, rsdmike approved these changes

2024-01-19 22:39 UTC, merged